package chapter05.practise.org.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table weather
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Weather {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     * Database Column Remarks:
     *   风速
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.speed
     *
     * @mbg.generated
     */
    private Long speed;

    /**
     * Database Column Remarks:
     *   温度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.temperature
     *
     * @mbg.generated
     */
    private Long temperature;

    /**
     * Database Column Remarks:
     *   露点温度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.dewPointTemperature
     *
     * @mbg.generated
     */
    private Long dewpointtemperature;

    /**
     * Database Column Remarks:
     *   降水量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.rainFall
     *
     * @mbg.generated
     */
    private Long rainfall;

    /**
     * Database Column Remarks:
     *   相对湿度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.relativeHumidity
     *
     * @mbg.generated
     */
    private Long relativehumidity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.id
     *
     * @return the value of weather.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.id
     *
     * @param id the value for weather.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.date
     *
     * @return the value of weather.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.date
     *
     * @param date the value for weather.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.speed
     *
     * @return the value of weather.speed
     *
     * @mbg.generated
     */
    public Long getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.speed
     *
     * @param speed the value for weather.speed
     *
     * @mbg.generated
     */
    public void setSpeed(Long speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.temperature
     *
     * @return the value of weather.temperature
     *
     * @mbg.generated
     */
    public Long getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.temperature
     *
     * @param temperature the value for weather.temperature
     *
     * @mbg.generated
     */
    public void setTemperature(Long temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.dewPointTemperature
     *
     * @return the value of weather.dewPointTemperature
     *
     * @mbg.generated
     */
    public Long getDewpointtemperature() {
        return dewpointtemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.dewPointTemperature
     *
     * @param dewpointtemperature the value for weather.dewPointTemperature
     *
     * @mbg.generated
     */
    public void setDewpointtemperature(Long dewpointtemperature) {
        this.dewpointtemperature = dewpointtemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.rainFall
     *
     * @return the value of weather.rainFall
     *
     * @mbg.generated
     */
    public Long getRainfall() {
        return rainfall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.rainFall
     *
     * @param rainfall the value for weather.rainFall
     *
     * @mbg.generated
     */
    public void setRainfall(Long rainfall) {
        this.rainfall = rainfall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.relativeHumidity
     *
     * @return the value of weather.relativeHumidity
     *
     * @mbg.generated
     */
    public Long getRelativehumidity() {
        return relativehumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.relativeHumidity
     *
     * @param relativehumidity the value for weather.relativeHumidity
     *
     * @mbg.generated
     */
    public void setRelativehumidity(Long relativehumidity) {
        this.relativehumidity = relativehumidity;
    }
}